### ISSUE TITLE
raw selectors

### ISSUE THREAD

**Issue by cztomsik** [css-modules/css-modules#10]
I really love the idea - it's the way how we should all write CSS from now! The thing is... there's a lot of existing unmodular CSS libraries and some of the frameworks even use tagnames in selectors.

Is somehow possible to import raw selectors? If I understand this correctly it's limited to classnames. This is all cool and great as long as we are writing all the CSS from scratch which is little unrealistic. It would be **very welcomed** feature if we could import raw selectors in any kind of "hacky" way because this would allow us to use modules right now - it does transpiling anyway so it should be possible, right?

Or how about supporting this via some kind of plugin so it would be optional & discouraged but possible for people who knows what they're doing?

**Comment by sokra** [comment]
You can use `:global` to define raw selectors: `.local :global(.active) {}` is `.rand123 .active {}`.

**Comment by cztomsik** [comment]
so I can create new module and export things from global context... nice, thx :)

**Comment by Chrisui** [comment]
@sokra are there any plans to support extending from global selectors?

Use case being similar to above where you have a global library you want to make use of but keep your consumption of exported class names consistent and tidy.

Ie. something similar to this...
```css
.btn {
    extends: global(btn);
}
```

would give exported class names...

```js
{
  btn: 'btn--9guv3 btn'
}
```

**Comment by Chrisui** [comment]
Btw I'm using [css-loader](https://github.com/webpack/css-loader) hence the `extends:` syntax :)

**Comment by geelen** [comment]
I like this! It should be pretty simple to implement & could really ease some folks' transition to using CSS Modules.

What do you think, @markdalgleish?

**Comment by markdalgleish** [comment]
Yeah, this looks like a great idea to me.

**Comment by sokra** [comment]
`composes: btn from global;`?

**Comment by markdalgleish** [comment]
@sokra's syntax makes the most sense to me.

**Comment by geelen** [comment]
That syntax looks really awkward to me, but it also makes the most sense I think. I thought you'd maybe want `composes: global(col-4-sm) from "./bootstrap.css"`, but then I realised you could just do this:

```css
@import "./bootstrap.css";
.foo {
  composes: col-4-sm from global;
}
```

**Comment by Chrisui** [comment]
+1 `composes: btn from global;`

**Comment by yoni-tock** [comment]
Also agree with that syntax :).

Relatedly, any advice on how to transition to css modules? One problem I'm bumping into is that local selectors are not very specific (on purpose) but it means that my local classes are easily overridden by styling on the parent, or other nested global classes from our (admittedly poorly designed) existing CSS. I can manage by refactoring on a case-by-case basis, but it's definitely a pain

**Comment by geelen** [comment]
I've been thinking about this comment a lot, @yoni-tock. I think the solution is rather than try to increase specificity of the styles *you* write, it's to avoid including the global styles in the first place. I've been tossing ideas around on this here: https://github.com/css-modules/css-modules/issues/17

So let's say you have a huge file with all your "old" styles in it. I'd love for there to be a way to include it as a CSS Module such that none of the styles get loaded by default. For example:

```css
body {
  background-color: black;
}

h1 {
  font-size: 4rem;
}
```

could get turned into:

```css
.tag__body {
  background-color: black;
}

.tag__h1 {
  font-size: 4rem;
}
```

(hat tip @markdalgleish)

Then, you need a way to apply the globals you *want* and leave the ones you *don't*. That's the tricky part!

**Comment by yoni-tock** [comment]
The challenge with just not including globals is that we'd still need to rewrite everything to reference the new CSS modules style files. One example of this might be a single page app using react-router, and we want to refactor one of the routes at a time to use CSS modules. Or alternatively, I want to refactor all my buttons to use styling from CSS modules without refactoring all my divs and h1s. Unfortunately, this kind of incremental refactor is inherently difficult because you can't isolate the components from the global styling. 

The only thing that I can think of is to mind for me is having some mode for "super specific local CSS" that adds some equivalent to reset.css to everything and slaps `!important`s on all the styling. The migration strategy then would be after all the global stuff is migrated to use CSS modules you turn off this mode. Even this seems pretty fragile though, so your solution in conjunction with composition might be the only real option.

At the moment, we're going to try doing it incrementally by starting with our most specific styling and refactoring conflicting issues as needed. We'll see how quickly we get stuck, haha

**Comment by sergeylukin** [comment]
Specificity issues aside, CSS Modules can easily live side by side with existing stylesheets. No need to force one into another in my opinion. What do you think?

**Comment by studiosciences** [comment]
For what it's worth. I'm approaching this problem the opposite way. CSS for CSS Modules should be flat, clean class, and our legacy selectors are nested and use too many element selectors (probably other peoples too).

I wrote a postcss-plugin to enable backporting of css-modules to some legacy classes, using a similar syntax as composes:

    .btn {
        mixin: default from "../css-modules/button.css";
    }

    .btn-fancy {
        mixin: btn;
        color: pink;
    }

It basically mashes together postcss-modules-extract-imports and postcss-import. Conceptually it does something very different than composes, but it is generally compatible with css written for CSS Modules. This mixin only grabs a class and it's nested children.

Composing globals, even as @geelen suggested in #17, doesn't seem to provide a great migration path, though it would enable one to write a component with only local styles.

**Comment by flying-circus** [comment]
But  if we are  really talking about sth global why we should work with it in the context of local css?(like the idea of `composes: btn from global;`)

In the beginning I thought that the following was such a lame approach  but writing it down seems to make some sense. We can bypass css-modules completely, and with the help of an  optional  helper object our code turns from:

```
//styles is the imported CSS modules
<div class={ styles.wrapper } />
```
to:
```js
//css strings helper object, which preferably it could be an ES6 Proxy to get rid of the spaces
let bs = {
  label_success: ' label label-success '
}

//our component simply  becomes

<div class={ bs.label_success + styles.wrapper } />

```
