### ISSUE TITLE
Cannot resolve paths to image files inside CSS module file

### ISSUE THREAD

**Issue by MrFirthy** [css-modules/css-modules#101]
Hi,
I'm new to CSS modules so apologies if this has been raised before, but I cannot seem to reference an image file inside my `.css` file without css-loader throwing the following error:

```
Module not found: Error: Cannot resolve 'file' or 'directory' /assets/img/image.svg in /Path/to/project/src/static/app/components/common
```

Each of my `.css` CSS module files sit in the same directory as the component `.jsx` file they style, and my file structure looks like this:

```
| app
    | components
       | common
            .jsx file
            .css file
| dist
    | assets
        | img
            image file
```

So I'm essentially trying to reference the image file from the CSS file. I am using Webpack and `style-loader` and `css-loader` to compile the CSS module files into one `.css` file.

Is this possible? Thanks in advance.

**Comment by MrFirthy** [comment]
For anyone having a similar issue, I ended up using [file-loader](https://github.com/webpack/file-loader) to handle the icons inside components that are referenced in CSS modules. This wasn't a CSS modules issue but might be useful to someone.

**Comment by sullenor** [comment]
Hi, 
I don't remember the exact error name, but this is a common issue for the webpack newcomers.

As you probably know, webpack treats all resources as commonJS modules. So, if the provided resource isn't a commonJS module (css file for example), you have to specify a custom loader for it (css-loader for example). Also for pictures and other static files.

I'd like to suggest you to try [url-loader](https://github.com/webpack/url-loader) instead of file-loader, because it provides you possibility to inline pictures/fonts which can be convenient sometimes.
