### ISSUE TITLE
How to use external libraries

### ISSUE THREAD

**Issue by sarink** [css-modules/css-modules#109]
I am working on a project that uses css-modules and am consistently being faced with this problem:

We want to use some library that renders a React component.

This library will render some markup like

```
<div class='foo'>
  <div class='bar'> </div>
</div>
```

Now, how am I supposed to style the `foo` and `bar` classes?

So far, the best I've come up with is...
Build a wrapper component which wraps the `foo` div in `<div styleName="myWrapper">`, then write some css like

```
.myWrapper {
  :global {
    // copy-and-paste all the css from whatever library, because you can't `@import` anything inside of a :global selector

    .bar {
      // apply any overrides, but remember, since you're nested, you can't `compose` anything
    }
  }
}
```

Is there a better way to do this? Having such poor support for existing libraries is making css-modules really difficult to use.

**Comment by StevenIseki** [comment]
Hi @sarink in my opinion if the global css modules you are trying to import can be re-used as a general css module by many componets, you should publish them to npm. This way you can easily import the module and use it in your components.

I have a few examples of this:
- [bootstrap-css](https://github.com/StevenIseki/bootstrap-css)
- [css-skeleton](https://github.com/StevenIseki/css-skeleton)
- [pure-css](https://github.com/StevenIseki/pure-css)

**Comment by sarink** [comment]
@StevenIseki That's a nice solution, but it's just not very feasible or realistic. There are thousands of libraries out there, building and maintaing a css-modules-compatible fork of each one is ridiculous.

**Comment by StevenIseki** [comment]
all they really need to do is add a **package.json** and `npm publish` the module. So it doesn't seem too difficult to me.

**Comment by timaschew** [comment]
Is there any option to load css globally without using `@import`, instead using `require` and with one loader definition in the webpack config?

**Comment by SohKai** [comment]
@sarink I'm having trouble with something similar, trying to use React-Bootstrap (or rather, make sure that it still works afterwards), bootstrap, and CSS Modules. @StevenIseki's done some great work with [bootstrap-css](https://github.com/StevenIseki/bootstrap-css) but unfortunately if other libraries, ie. React-Bootstrap, rely on the global class names, they won't work anymore.

What I've settled on for now, is just to load the external library's CSS as-is, without any CSS Modules modifications, and then if I need to compose a style from it, I use `composes: foo from global'. If you can load the external CSS, you shouldn't need to copy over the styles, and since I assume it's out of your hands, there's no benefit in you modularizing the library's CSS.

As for overriding styles, this seems to be more of a component design issue than with CSS Modules (due to it's limitations; see #33). If you can modify the library, can you add a `className` parameter or additional theme extensions? If you can't, then you can either make wrapper components like what you've been doing, or use a global stylesheet whose sole purpose is to apply overrides for the library. Since I'm working with React-Bootstrap, I supply my overrides either through components' `bsClass` properties in wrapper components or add styles to a global stylesheet that supplies default overrides for bootstrap. To enable global theme changes, I use [rethemable](https://github.com/andreypopp/rethemeable).

**Comment by themitchy** [comment]
We hit some similar issues and solved it with `@import`. Check out #65, there are a few other solutions there as well.

**Comment by jdelafon** [comment]
I ran many times through the issues mentioned above and still don't understand what the solution is to **overriding** a class name from an external component (loading external libraries is ok). Can somebody please suggest something understandable? (Unlike "I used @import and it worked").

I have a grid with deeply nested components and apparently my loader does not understand nested css (which I never needed until now).

**Comment by dvkndn** [comment]
@jdelafon I used @import and it worked. Detail: https://github.com/css-modules/css-modules/pull/65#issuecomment-248280248

**Comment by outdooricon** [comment]
to be clear, @import will not work if you are using sass because sass will inline the content. So you will either need to wrap the import in `:global` or import the css your component js instead using the `!style!css` prefix to skip the module call.

**Comment by TrySound** [comment]
See https://github.com/css-modules/css-modules/issues/147

**Comment by kricore** [comment]
Sorry to hijack. This is a crude solution, but if you just want to prototype your app or looking for something quick and dirty it might do the trick.

https://gist.github.com/kricore/505c14fb9c69d77184458499707c2d98

**Comment by trainoasis** [comment]
This is still not possible?
