### ISSUE TITLE
Files used to compose other classes are not parsed with preprocessors

### ISSUE THREAD

**Issue by jalooc** [css-modules/css-modules#110]
When using `compose` with external `scss` file, which itself isn't imported in the project in any other way, the class which `compose` is used on is not parsed with sass. E.g. I have a file `forms.scss`:

```
.input {
  background-color: rgba(#fff, .2);
}
```

and a file `component.scss`:

```
.component-input {
  composes: input from 'forms.scss';
}
```

The `forms.scss` file is not imported in any other way to the project then by the above `compose`. The `component.scs` file is imported using `import` into some js file and the `component-input` class is applied to some html element. Then what I see in a browser is that the html element has a following style: `background-color: rgba(#fff, .2)`, where it should have been processed to `background-color: rgba(255, 255, 255, 0.2)` by sass preprocessor.

**Comment by bkonkle** [comment]
I believe this is actually related to https://github.com/webpack/css-loader/issues/131. I'm working on a pull request for that issue, so keep an eye on it.

**Comment by delijah** [comment]
Also related to #170.

**Comment by bkonkle** [comment]
You might be interested in my comment here: https://github.com/webpack/css-loader/issues/131#issuecomment-235054165

I was able to solve this issue - it was actually a Webpack misconfiguration.

**Comment by delijah** [comment]
Thanks for the input. #170 addresses a different issue than https://github.com/webpack/css-loader/issues/131#issuecomment-235054165.

With using the importLoaders config option, you can tell the css-loader how many loaders of the same loader config option shall be applied.

#170 is saying something else. Another example:

webpack config
```
loaders: [{
    test: /\.css$/,
    loaders: [ 'style', 'css?modules&camelCase' ],
}, {
    test: /\.sass$/,
    loaders: [ 'style', 'css?modules&camelCase&importLoaders=1', 'sass' ],
}]
```

abc.sass
```
.title
  composes: title-font from "./styles.css"
```

styles.css
```
.title-font {
  color: red;
}
```

Expected behaviour: For the import of "styles.css" css-modules must use the loader for .css files.

Current behaviour: css-modules just uses the same loader as the current code is executed with (in this case the "styles.css" file will be imported by the .sass loader, which is wrong).
