### ISSUE TITLE
Changing composition syntax

### ISSUE THREAD

**Issue by calebmer** [css-modules/css-modules#122]
After a brief preview of your documentation I have not seen a way to change the syntax for `compose`. I don't like this syntax for a number of reasons and would like to see an alternative. The reason I see the current `compose` rule as non-idiomatic include:
- Spaces typically delineate multiple values. With the `compose` rule we have text like `large from "../mixins.css"` which does not adhere to this general rule.
- Identical rules replace, not add to. In CSS multiple rules "cascade" replacing older ones. This is not the case with `compose`, rather every `compose` rule applies.
- No way to put all statements in a single rule. This is similar to above, from what I've seen from the current syntax there is no way to consolidate all the `compose` rules into one.

A preferable syntax for me would be similar to SASS's `@extend`. Maybe `@compose normal` and `@compose normal from "../mixins.css"`.

**Comment by giuseppeg** [comment]
How about `@apply`?
Would it be doable to kinda rewrite CSS Modules to use CSS `@apply` (and maybe `:scope` by default) to achieve the same results? cc @geelen

**Comment by calebmer** [comment]
Yeah, that seems much more idiomatic than a CSS rule.

**Comment by chrislloyd** [comment]
I think the argument in favor of allowing multiple `composes` is because composition should be idempotent, though in practice it can lead to declaration order affecting styles.

I do however, think it needs to change. I've seen code like this:

```
composes: foo from "./foo.css";
composes: bar from "./bar.css";
```

which ultimately ends up like:

```
:root {
--styles: "./bar.css";
}
composes: foo from var(--styles);
composes: bar from var(--styles);
```

I'm a fan of fixing this by changing `composes` to use syntax similar to the CSS3 background property:

```
composes: foo from "./foo.css", bar from "./bar.css";

// or

composes: foo from "./foo.css",
          bar from "./bar.css";
```

I think this would also address a common cause of confusion where people don't know wether to put commas between their composed classes. With this syntax both commas and not would be valid.

```
composes: foo,
          bar,
          baz1 baz2 from "./baz.css";
```

Happy to work on a PR to help resolve this issue.

**Comment by geelen** [comment]
On board with this change definitely. The intent of multiple composition is that the _className_ and the _fileName_ combine to be meaningful. Hence something like

```css
composes: type-14pt-small margin-top-3rem from "./utils.css";
```

is not desirable, but

```css
composes: 14pt light from "./typography.css";
composes: mt3 from "./layout.css";
```

is. But I don't see any problem with changing the syntax to:

```css
composes: 14pt light from "./typography.css",
                   mt3 from "./layout.css";
```

Bit worried about mixing and matching spaces & commas though. Maybe you could clarify that last example @chrislloyd?

The other thing, if you're writing a lot of these composition statements, is you could write a small css transformation in PostCSS and generate `composes` statements from your own syntax. I experimented with [an idea here](https://github.com/geelen/glenmaddern.com/blob/master/src/lib/footer.css) ([implementation here](https://github.com/geelen/glenmaddern.com/blob/master/src/css.js#L4-L24)) last year but if I were doing it today I'd do something like:

```css
.foo {
  @composes("../shared") {
    typography: 14pt light;
    layout: mt3;
  }
}
```

That could compile down to the current CSS syntax just by dropping in the plugin in front. But, if you don't want to go that far, I'd happily merge/release a PR doing my suggestion above. The code you'd need to change is here: https://github.com/css-modules/postcss-modules-scope/blob/master/src/index.js#L95

<3 to you all.

**Comment by chrislloyd** [comment]
I can one up clarifying the example :) Take this [Ohm file](https://gist.github.com/chrislloyd/9e02e50601f0fd291161eb139b7b4e14) and upload it to the [web editor](https://ohmlang.github.io/editor). You can also paste in the examples to verify the grammar and see the parse tree.

The biggest downside I can see is that class names called "from" might be disallowed, but that could also be fixed by rejiggering the grammar.

**Comment by geelen** [comment]
I... couldn't make that work lol

But are you suggesting that `composes: x, y from "z"` means:

```css
composes: x;
composes: y from "z";
```

or `composes: x y from "z"`?

**Comment by chrislloyd** [comment]
First example. If no from parameter is specified, defaults to composing
from local file.

**Comment by geelen** [comment]
Ok awesome, that's a 👍 from me.

**Comment by giuseppeg** [comment]
Wouldn't it be easier to remove inline imports and encourage top level ones using JS modules' syntax 
```css
import { --foo, --bar } from 'file.css';
```

or more CSS-y

```css
@import { --foo, --bar } from 'file.css';
```
?

`foo` and `bar` are custom properties groups that can be used with `@apply`. They can be used as follow 

```css
.MyComponent {
  @apply --foo;
  @apply --bar;
}
```

To make the implementation simpler custom properties rules groups could be compiled to static css. For example:
```css
:root {
  --foo: {
       background-color: hotpink;
  };
}
```

becomes

```css
.--foo {
   background-color: hotpink;
}
```

And in the end the same idea of CSS Modules applies:

```html
<div class="--foo MyComponent"></div>
```

Why is this a good idea?

Because it makes CSS Modules code standards compliant (except for the imports part) and it'd be easier to port a codebase to some other system that uses [regular] CSS.

Question is this really a good idea or a terrible one? :)

**Comment by geelen** [comment]
That's actually what [postcss-modules-values](https://github.com/css-modules/postcss-modules-values) does, but composition is kept separate. We also deliberately avoided clashing with any current or future CSS concepts because passing values between files is very different to the way CSS Variables actually work. Composition isn't really similar to `@apply` either, it's much more like Sass's `@extend`. But, again, because it _isn't_ an attempt to replicate one of these behaviours we _definitely_ don't want to confuse the users by overloading known terms.

**Comment by giuseppeg** [comment]
<blockquote>because passing values between files is very different to the way CSS Variables actually work</blockquote>

Fair enough, I trust you on this since I haven't had the chance to think this through.

<blockquote>Composition isn't really similar to @apply either, it's much more like Sass's @extend</blockquote>

Does it make any difference in CSS Modules land? I don't think so.

**Comment by giuseppeg** [comment]
(if you want I can delete my comments to remove some "noise" from this issue)
