### ISSUE TITLE
shadow dom and css modules

### ISSUE THREAD

**Issue by pavel06081991** [css-modules/css-modules#124]
Could you please clarify when shadow dom is available in browsers, will we still need css modules?

**Comment by 0xR** [comment]
Shadow DOM also scopes CSS so there are no accidental naming conflicts. CSS modules does more than just name mangling to avoid naming conflicts though. Composing styles is also a big part of it. This even allows you to reuse CSS across CSS files. Because this composition works by just add additional CSS classes to a Node there is no additional CSS generated.

So if you're using CSS modules just for name mangling then you don't need it when shadow dom is available. However, if you're using multiple CSS files with composition you will still benefit from CSS modules.

**Comment by adam-beck** [comment]
@0xR but the ShadowDOM will use inheritable CSS values. So if I understand what you have written that would be the same as composing styles.
