### ISSUE TITLE
Philosophy nested selectors, tag selectors

### ISSUE THREAD

**Issue by aft-luke** [css-modules/css-modules#131]
I'm hoping someone can clarify a conceptual issue I'm having with css modules. Are we throwing away nested selectors to use css-modules? I understand some of the problems it introduces with regards to specificity of selectors and complex overrides/inheritance... but what's the alternative? Do I have to attach a class to absolutely every element I want to style?

```
<div class="my-component">
  <header>
    <h1>Some Component</h1>
    <h2>subheader</h2>
  </header>
</div>
```

If I were doing this without css-modules in stylus, I would simply write:
```
.my-component
  display flex
  header
    display flex
    h1
      font-size 2em
    h2
      font-size 1.5em
```

And the module is somewhat "contained". Not perfect, but it goes a very long way to keeping things modular. 

If I want to approach this from a css-modules angle, how do I do the same?

```
.my-component {...}
.header {...}
.h1 {...}
.h2 {...}
```

And I have to attach a class to every single element? Is it not possible to export tag-level selectors as js modules?

```
.my-component {...}
header {...}
h1 {...}
h2 {...}
```

```
// jsx
<div className={styles['my-component']}>
  <header>
    <h1>Some Component</h1>
    <h2>subheader</h2>
  </header>
</div>
```
What I really, really don't want to do is have to attach a class to every single element in my entire dom.

```
// jsx
<div className={styles['my-component']}>
  <header className={styles.header}>
    <h1 className={styles.h1}>Some Component</h1>
    <h2 className={styles.h2}>subheader</h2>
  </header>
</div>
```

This is very verbose and introduces a whole lot of boilerplate, and makes the html more difficult to read (imo).

**Comment by rossPatton** [comment]
i'm not a css-modules contributor, but you should just attach a class to every element you wish to style, imo. this isn't a new thing with css modules, the atomic approach works the same way.

you type more in the html yes, but you save on css size and css complexity. a lot of people seem hesitant to take this approach, but from my experience with both atomic css and css-modules, it saves you a lot of pain in the long run (and tends to be more performant, as you actually end up writing less css most of the time)

**Comment by aft-luke** [comment]
Thanks for the comments @rossPatton . I'm not familiar with atomic, but I will take a look. 

I guess I just disagree with the philosophy of css-modules. "Every element you wish to style" happens to be every element in the entire application, which means every single tag of html will have `class=""`, and every single css file just grew by a lot. 

As far as performance goes, I haven't looked too deeply into inlining styles vs bundled minified css vs the exporting of js classes that css-modules offers. Aren't we just increasing our js bytecount (more modules) as well as our css filesize (more selectors) with css-modules, though? Or do you mean performance in terms of the dom selector engine?

**Comment by rossPatton** [comment]
There are always going to be tradeoffs, but in my experience the atomic / css-modules approach means LESS css, not more.

In the case of an atomic approach (which you can easily use with css-modules), you write rules that do one thing, and then compose them together to style an element however you like. I find that when I have a strong base atomic system (a grid, some gutter and type styles) setup, I almost never have to write new css. I just compose pre-existing styles to get the effect I want. In my case, every time I've applied this approach to a pre-existing site, i've been able to cut css size by hundreds of kbs (to be fair, those are big sites, your results may differ). Combine this with css-modules, only loading the css rules actually used on the site, and you get even better results. 

As for performance, the dom can't start rendering until it's downloaded and parsed all the css, which is why inlining has become so popular. No css in the head to parse, the browser can start rendering sooner.

I don't do js inlining so I can't speak to how that works out, but css modules helps your time to first byte by dramatically decreasing the total css on the page, meaning the browser can start rendering the page sooner. The rules are appended to the head in a style tag just like normal css use, there will just be a lot less of it.

**Comment by joshwnj** [comment]
> There are always going to be tradeoffs

Agreed, this is absolutely a tradeoff. On one hand it can be a pain to have to set the `className` of every element, on the other hand this is a fairly "programmable" task and there is plenty of value to be gained in return.

@aft-luke to take your example, the benefit of a classname on every element is that you no longer need to compete on specificity.

If you have `.my-component header { ... }` it will work fine until there are subcomponents that also have a `header`. At this point we're back to fighting with globals.

You could also use `.my-component > header { ... }` which will work fine until the html structure changes and `header` is no longer a direct descendent. 

Notice that in both of the examples above, when it fails it's a silent failure. Your css code will possibly one day stop behaving how you expected it to, and it will be due to a change somewhere else.

So for the low cost of giving each element a `className`, we can target the exact element we want to style without having to continually raise the specificity of selectors whenever changes to html or css introduce an unintended cascade.

> Are we throwing away nested selectors to use css-modules?

Nope, you can still do `.my-component header { ... }` with css modules, you just won't get the benefit of it in this case.

Does that clear up your question?

**Comment by aft-luke** [comment]
Thanks @joshwnj for the clarification. Perhaps I will just take your word for it and try this system for a whole app. Maybe I will grow to like it. I definitely see the advantages, particularly as the dom shape of components changes... which was something I hadn't considered.

**Comment by joshwnj** [comment]
cheers @aft-luke , let us know how you go. I've been using css modules on a pretty large and non-trivial frontend, coming up to 1 year and it's definitely removed a lot of the headaches of similar projects in the past.

**Comment by NevenLeung** [comment]
I have found some useful example here, [css-modules-by-example](https://www.javascriptstuff.com/css-modules-by-example/).

It includes combined class names, nested class names, and tag names.

**Comment by bhavyaw** [comment]
@joshwnj,

Just a few thoughts...

> @aft-luke to take your example, the benefit of a classname on every element is that you no longer need to compete on specificity.

- What's the problem with competing with specificity on the component level. It's fairly easy. It's a fundamental feature of CSS language. I though **css modules was supposed to augment css** and not create a separate language of its own.

> If you have .my-component header { ... } it will work fine until there are subcomponents that also have a header. At this point we're back to fighting with globals.

- There's a difference b/w fighting globals at the component level and app level. Even in javascript modules we can define globals at the module level. Can you think of working without globals at the module level in JavaScript ?

> You could also use .my-component > header { ... } which will work fine until the html structure changes and header is no longer a direct descendent.
> 
> Notice that in both of the examples above, when it fails it's a silent failure. Your css code will possibly one day stop behaving how you expected it to, and it will be due to a change somewhere else.

- **How often do you think the structure changes in most apps** ?. Initially while building the apps, there might be a little re-write. But once a app is built, most of them don't get updated frequently. Just for this circumvent the a little trouble while re-writing html we are letting go of basic features of css language - nested selectors ?

> So for the low cost of giving each element a className, we can target the exact element we want to style without having to continually raise the specificity of selectors whenever changes to html or css introduce an unintended cascade.

Low Cost ? Do you realize the amount of extra work it takes to put class attribute on top on every element that needs to be styled ( uniquely ) esp. in a large app. This really hurts development speed and development experience.
