### ISSUE TITLE
Expected behavior documentation (spec?)

### ISSUE THREAD

**Issue by aft-luke** [css-modules/css-modules#145]
I'm looking at my css-modules output and it seems extremely verbose. Is it the expected behavior with compose to copy the entirety of the composed file into the output (recursively) instead of only those classes referenced in the compose (and their requirements)? This gets hairy quickly, particularly if composing composed components.

styles

```
.button
  composes a-button from '../styles/button.css'
```

buttons

```
.base
  cursor pointer
  border none

.a-button
  composes base
  background-color blue

.b-button
  composes large from './typography.css'
  background-color green
```

typography

```
.large
  font-size 24px
  font-weight 500
```

Generated output for styles file:

```
// all the base stuff (expected)
.base_hash
  ...
// all the a-button (expected)
.a-button_hash
  ..
// all the b-button stuff (huh?)
.b-button_hash
  ...
// all the stuff b-button uses (... what?)
.large_hash
  ...
```

I just don't get this output?

**Comment by geelen** [comment]
Nope, this is expected behaviour. Composition first includes the target file in its entirety then attaches the composed class name to the output. So if `styles` references `buttons` which references `typography` those will all get included into the output. The idea is not to be tracing through single class usages in massive CSS files, the idea is to allow you to break up your massive CSS files into small, semantic pieces.

Each file only gets included the once, though, so there's no duplication in the output. As soon as one file references `typography` it will be included in the output. But it doesn't matter how many times it's used.

Does that make sense?

**Comment by aft-luke** [comment]
This does make sense thanks for the clarification. Given this, is it a legitimate concern to worry about enormous style declarations? Browser taxing? What is the recommended layout for breaking up "global" styles without generating a ton of waste?

~luke

**Comment by aft-luke** [comment]
Sorry, I had some more time to think about this and perhaps I misunderstood your response. If I were to, say, run a cssmodule compiler against individual files one at a time, compared to all in one sweep, would that change the output? If that is the case I need to think up a new strategy. I wrote a pipeline to take stylus, convert it to css, convert that to css module syntax, then compile the result into a clojurescript module. I do this one at a time, from the perspective of the `css module syntax input -> compiled css`, and perhaps that would (and is) cause(ing) a whole lot of duplication. 

~luke
