### ISSUE TITLE
Who's using CSS Modules?

### ISSUE THREAD

**Issue by athyuttamre** [css-modules/css-modules#153]
Perhaps it's a good idea to create a list of companies / organizations using CSS Modules in production. If you use it, could you comment below with what your scale is and how it's been working for you so far?

**Comment by geelen** [comment]
This is something I'd like to have a section on the website, once, you know, we have one :)

**Comment by dvkndn** [comment]
Our team are using it, everyday, at http://quoine.com (http://beta.quoine.com to be exact, but it will become official in next few weeks, so I guess I can count it as production)

We are building a trading app for crypto currencies, I think it can be called "complex".

However, our styling system is pretty simple since we switched to use CSS Module with the magical `compose`.

We met 2 major issues, first is a theming system, which I found a solution later (https://github.com/css-modules/css-modules/issues/160) and the other one is lack of getting started document (some people are not easily understand what is it at first)

**Comment by langri-sha** [comment]
It would also be extremely helpful to others to list references to OSS projects that make extensive use of CSS modules. I would really like to see how others like @dvkndn are practically applying `composes` to make their styles robust and easier to read.

For instance, https://github.com/react-toolbox/react-toolbox/ really got me convinced to move to PostCSS and CSS modules, but therein `--z-index-${layer}` variables are added to `variables.css` and lengthy declarations are written everywhere else from then onwards, but to me the following would make a lot more sense:

```
.backdrop {
  composes: overlay from 'styles/layers';
}
```

Good use examples we can read and share with our colleagues would definitely help everyone maintain high standards.

**Comment by leerob** [comment]
Hey, here from the future 6 years later. A lot of people are using CSS Modules now, probably more than we should list 😄
