### ISSUE TITLE
extending :global classes 

### ISSUE THREAD

**Issue by sagar-ganatra** [css-modules/css-modules#154]
Say I have a set of classes in typography.scss which are marked as global:

typography.scss:

```
:global {
     .pageHeader {
          font-size: 4rem;
      }
}
```
In my React component I can use 'pageHeader' class as it is; however when I try to extend it in a scss file

componentA.scss

```
@import 'typography.scss';  
 .header {
    @extend .pageHeader;
 }
```

This wouldn't work and fail silently. 

Is there anyway I can extend a :global class?

**Comment by geelen** [comment]
Interesting, I'm guessing because Sass is confused by the `:global` bit. Personally, I'd do something like:

```scss
/* typography.scss */
%bigFont { font-size: 4rem; }
```

```scss
/* globals.scss */
@import 'typography.scss';  
:global {
  .pageHeader {
    @extend %bigFont;
  }
}
```

```scss
@import 'typography.scss';  
.header {
  @extend %bigFont;
}
```

This makes your intent a bit clearer (`%bigFont` is something to be shared, `.pageHeader` is a global class). Of course, you could always just use `composes` as well, and drop Sass altogether.

Hope this helps!
