### ISSUE TITLE
composes issue

### ISSUE THREAD

**Issue by imseanpan** [css-modules/css-modules#155]
HI，
I download this demo [outpunk/postcss-modules-example](https://github.com/outpunk/postcss-modules-example).
When i remove this code  **composes: figure from './mixins.css';** in css/style.css.
After build i think the **figure** is not in build/style.css. But It still exists.
If I just want to  quote I used to style in build/style.css.
How can i do?????

**Comment by dvkndn** [comment]
@imseanpan You are misunderstanding how CSS Modules works.

CSS Modules doesn't care which class you use and which you don't. What CSS Modules care is which file you want to import, and it will change the class name inside that file, and return a new file with all class hashed, and an object for you to use the new classes.

Therefore, if you have imported `mixins.css` somewhere, or compose some classes from `mixins.css` (not `figure`), `figure` will always be in `build/style.css`, no matter you compose it or not, because it is in `mixins.css`, and `minxins.css` is imported.
