### ISSUE TITLE
How to alter style of child component if I don't control that component?

### ISSUE THREAD

**Issue by terencechow** [css-modules/css-modules#167]
I have pushed a component to my private github. I can install the component from separate repos with any `package.json` that has: 
`childcomponent: git+https://token:auth@github.com/myrepo/childcomponent`.

My childcomponent src file looks something like this:

```
import styles from './styles'
...
return (
<div  styles={styles.childComponent}>
...
</div>)
```

The above is compiled to es5 file with webpack, hence the styles are inherently included in the js file.

Now I've come across a scenario where I would like to import this childComponent in a separate repo but also change the styling a bit:

```
import parentStyles from './parentStyles'
<MyParent>
 <ChildComponent styles={parentStyles.someSpecialStylesForThisScenario} />
</MyParent>
```

My problem is that `MyParent` cannot take advantage of the CSS_modules `composes` keyword because `MyParent` doesn't have the source css file for `ChildComponent`. Hence I can't `composes from ChildComponent.css`.

I'm wondering how this is generally handled? Do I have to modify `ChildComponent` to accept some props that manually change the style? 

I would really like something clean such that the parent style can `composes ChildComponent` because if I have to add some prop into every component that I publish on a repo, then it is a lot of rewriting of code, which is against the DRY principle and feels wrong. 

Keep in mind that I plan on reusing ChildComponent across projects

**Comment by terencechow** [comment]
I've looked into this further and I made my child component accept a props called customStyles.

The customStyles is the css modules from the parent and is added to the styles of the child as per below. 

Right now in the code I see that the custom styles overrides the childComponent styles when are the same attribute. However I can't confirm if this is guaranteed. Is the parent styles guaranteed to override any child components if done in this manner? If so, Why and if not Why Not?

ChildComponent
```
import styles from './styles'
...
return (
<div  styles={styles.childComponent + " " + this.props.customStyles}>
...
</div>)
```

Parent
```
import parentStyles from './parentStyles'
<MyParent>
 <ChildComponent customStyles={parentStyles.someSpecialStylesForThisScenario}  />
</MyParent>
```

**Comment by dvkndn** [comment]
> I'm wondering how this is generally handled? Do I have to modify ChildComponent to accept some props that manually change the style?

Yes I think you should. CSS Modules is not related to React, but in this case I guess you are using React, so it would be better if you can think like this:  "Is your ChildComponent allow outsider to changed it styles?". I think you shoudn't be afraid of "add some prop into every component", because that is logically correct. What you should be afraid is when a parent can change the child but the child have no idea about that.

I think this may sounds weird at first, but things will be simpler and more reasonable and predictable if you think like this. *A component should only be changed what it allows to changed.**

**Comment by dvkndn** [comment]
> Right now in the browser I see that the custom styles overrides the childComponent styles when they have the same attribute. However I can't confirm if this is guaranteed. Is the parent styles guaranteed to override any child components if done in this manner? If so, Why and if not Why Not?

The rule is styles that declared later will override styles that declared sooner. To know which is declared later, you must understand when those styles are imported (by CSS Loader - Webpack). It is not matter child styles or parent styles.

For example, in this case:
```js
import parentStyles from 'parent-styles.css';
import ChildComponent from 'child-component';
...
```
the child styles will override the parent styles, because it is imported later (it is imported by ChildComponent, and ChildComponent imported after parentStyles)

In your case, I guess you import ChildComponent before parentStyles, that's why parentStyles is override childStyles
