### ISSUE TITLE
Help dealing with weird use case

### ISSUE THREAD

**Issue by brianac** [css-modules/css-modules#168]
I was hoping someone here might know what my next steps might be regarding setting up CSS modules in my project. It's a weird use case I'm trying to cover here.

The project I'm working on deals with a bunch of embeddable widgets, each has their own iframe. 
The way we currently do CSS is it inject the compiled CSS files into each iframe as it loads.

I think the iframe is messing the way CSS modules wants to inline the styles. I can import a CSS modules file inside the iframe and will get the correctly constructed classNames but the styles won't be found since they're not in the iframe scope. 

What I'd like to do is have the CSS module classes compile to a specific file that I can then inject into the iframes so they can actually see the styles they need. Do anyone know if anything like this is possible currently? I'd rather not have to resort to building a custom loader if possible.

cc/ @markdalgleish

**Comment by geelen** [comment]
Interesting use case!

My first instinct is, because CSS Modules compiles everything to distinct names, that there's no harm in having more styles than you need. If you compile all the styles for the iframe and the outer stuff together and extract them (if you're using webpack the [extract-text-plugin](https://github.com/webpack/extract-text-webpack-plugin) will do that) and then attach them to _both_ the outer and the inner iframe context.

I'd say start by trying that and see how you go.

**Comment by dvkndn** [comment]
> there's no harm in having more styles than you need.

Moreover, you also don't need to worry about the size of the single extracted file, because by using `compose`, you moved the styles combination logic to JS/HTML files so the final css file size will be quite small, far smaller than if you export to multiple files I think.

**Comment by brianac** [comment]
Thanks for the tips. I'll give it a go :)

**Comment by brianac** [comment]
@geelen Unfortunately I don't think the extract-text-plugin will work for this example. I got it working fine our project but I don't think I can require the styles.css file I need into our file that injects the css into the iframe. 

Since they're now built into a seperate file now, the components within the iframe also can't require the files they need. Once again I think it's because the iframe is in the way so the magic the extract text plugin does to grab the css and point it in the correct place isn't working.

Do you have any other ideas? It's looking more and more like I might have to build a custom loader...

**Comment by brianac** [comment]
Any chance anyone else has some ideas? @geelen @dvkndn @markdalgleish ?

**Comment by dvkndn** [comment]
Hi @brianac , first, I think we need to clarify the "magic" behind CSS Modules and Extract Text Plugin (ie: how they works)

- CSS Modules **hash** your class selectors, and return an object contains the hashed classes. (For example, if you have `.text { ... }`, it will be transformed to `.text__h2hs8`, and the returned object has `{ 'text': 'text__h2hs8' }`, so you have the hashed class to use in your code)
- And that's all! CSS Modules **doesn't** care how to apply those css. The `style-loader` is the one who get all those (hashed) css and add them to your html using `<styles>...</styles>`. No one inline any styles. The *magic* happens because you *used* the hashed class and they also get added to your html.
- Now, Extract Text Plugin is some kind of an alternative to `style-loader`, which has no idea about CSS Modules. Instead of add css to your html using `<styles>` tag, this plugin moves all your css to a seperate file, and link to that file in your html (`<link>`). That's all about Extract Text Plugin: you receive a file containing all your css (with hashed class if you are using CSS Modules)

One more note, not really related to your situation but worth knowing:
- CSS Modules is actually just a spec. It has many implementations, one of them is the `?module=true` option in `css-loaders`. It is simple. It won't do many thing alone.

**Comment by dvkndn** [comment]
So, for your situation, I suggest you to try this: (I just explain @geelen idea)

1/ You have `style.css` as below
```css
/* styles.css */

.text {
  color: red;
}
```

2/ You import `style.css` in both your main page and your iframe
```js
/* file-in-main-page.js */

/* import here so it will be available in main page entry css file */
/* I'm not really sure about your webpack configuration, maybe you don't even need this */
import './styles.css';
```
```js
/* file-in-iframe.js */

import styles from './styles.css';
const App = () => (
  <div className={styles.text}>this text should be red</div>
);
/*...*/
```

3/ Now, after using ExtractTextPlugin, you will have a `<link>` to your bundled css file (you can check it at run-time to see). Something like this:
```html
<!-- index.html -->

<head>
  <!-- ... -->
  <link href="your-bundled-css.css" />
  <!-- ... -->
</head>
```

4/ If you see inside that bundled css, you will see your css with hashed classes. Now, inject that css into your iframe and tell us if it works or not

**Comment by brianac** [comment]
Thanks for the detailed answer, I appreciate the explanation but unfortunately I don't think this will work for us.
So for some more clarification on our use case, my team works on a widget that our customers embed on their websites, therefore we don't really have an index.html page to get the linked css. When I try to require the files into our javascript that constructs the iframe I get module import errors. 
The main problem the ExtractTextPlugin tries to solve is pretty much the opposite of how we construct our widget seeing as we want to bundle everything into one file to send down so I didn't think it would play nicely but was hoping there was a way to get it to work. I don't know that we will be able to solve this with existing tools as our project is very strange so will probably have to look at some other way to do this.

**Comment by dvkndn** [comment]
Oh sorry @brianac . I misunderstand your case in my answer :(

**Comment by brianac** [comment]
That's alright, I didn't really elaborate that much initially and I appreciate your detailed answer :)

**Comment by dvkndn** [comment]
Actually, I think this is an interesting use case, so if you found a good solution, please feel free to share :D I think people will face issues like this

**Comment by SeeThruHead** [comment]
I'm actually running into this today as well. We do something pretty similar.

I'm running a react app inside an iframe, and rendering the output to a different iframe.
The css modules styles show up in the iframe where the app is running, but not where it's rendering.
(I expected this, but I still need a way around it)
I think I just need a way to tell style-loader to use a different document.

**Comment by brianac** [comment]
@SeeThruHead Nice to know I'm not the only ones with weird iframe issues. I agree this is more of a loader issue but thought I'd see if anyone here could lead some knowledge.

Seems like the style-loader issue fix you posted would work for normal css but doesn't seem to like the css modules syntax for me. Have you had any of luck getting yours working?

**Comment by SeeThruHead** [comment]
@brianac I actually ended up removing style-loader, and doing this (in react)

```
import React from 'react';
import styles from './view.css';
const classes = styles.locals;

export default () => (
  <div>
    <style>{styles.toString()}</style>
    <div className={classes.container}>
      Hello World
    </div>
  </div>
);
```

**Comment by brianac** [comment]
Thanks for the tip. Just tried this and it works for us as well. I never thought of removing the loader.

It won't be the most elegant solution in our framework but this will work for us for now. I'll close this off. Thanks again for everyones help with this.

**Comment by dvkndn** [comment]
Should we add this to FAQ?
