### ISSUE TITLE
Some classnames can't be composed

### ISSUE THREAD

**Issue by narehart** [css-modules/css-modules#204]
I noticed when using CSS modules that some classnames are undefined when composed. For example, I have a file that contains classes for color:
```
.red {
  color: red;
}

.black {
  color: black;
}
```

When composing like so black returns undefined but red doesn't.
```
.link {
  composes: black from 'styles';
}
```

Is there something I'm missing? Let me know if you need more info.

**Comment by joshwnj** [comment]
What's the name of the file containing `.black`? `composes:` expects a path to that file.

eg. `composes: black from './styles.css';`

**Comment by edmcmanwich** [comment]
The files is at `src/styles/index.scss`. I have webpack setup to resolve the src directory and scss extensions.

I don't think this is a path issue. If I change the classname to `.blackish` it works.

**Comment by joshwnj** [comment]
Could you please set up an example repo on github so we can reproduce the error?

**Comment by edmcmanwich** [comment]
https://github.com/edmcmanwich/css-modules-bug-example

I noticed when setting up the repo that everything worked until I added postcss with cssnano so this might not be a css-modules problem but I'm not sure where the compatibility issue lies.

**Comment by edmcmanwich** [comment]
Setting `colormin: false` in the cssnano config fixes the issue. This might be related to https://github.com/webpack/css-loader/issues/316. Maybe cssnano is seeing something like `___CSS_LOADER_IMPORT___7___` and dropping the output?

**Comment by joezimjs** [comment]
I think that cssnano is changing "black" to "#000" because it's shorter. Not sure why it would affect a class name and it should happen after the modules are processed, so it shouldn't convert `compose: black from 'styles'` to `compose: #000 from styles`, so I'm not sure where the issue is happening, but that's definitely what it seems like it's doing.

**Comment by ben-eb** [comment]
@joezimjs cssnano expects valid CSS to be passed through - but as css-modules/css-loader are widely used I can make an exception for this. New installs will ignore the `composes` property.

https://github.com/ben-eb/postcss-colormin/commit/f0ef110adcc9d30f851795cec1d3a20cb6e5e8ca

**Comment by dvkndn** [comment]
> Not sure why it would affect a class name and it should happen after the modules are processed

@joezimjs CSS Nano happens **before** CSS Modules because Post CSS loader (which has CSS Nano) run before CSS loader (which has CSS Modules), as you can see in your webpack config:

https://github.com/edmcmanwich/css-modules-bug-example/blob/master/webpack.config.js#L37

```js
loaders : [
  'style',
  'css?sourceMap&-minimize&modules&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]',
  'postcss',
  'sass?sourceMap'
]
```

Anyway, thank to @ben-eb this is not an issue anymore :D
