### ISSUE TITLE
"#" id selectors are namespaced

### ISSUE THREAD

**Issue by aaronbeall** [css-modules/css-modules#208]
I wasn't able to find anything about this in the documentation. The description mentions "class names" but I did not see it mention "ids", however I'm seeing CSS Modules (used via webpack loader along with `postcss`) namespace the id selectors as well. 

For example, given this CSS:

```
.bucket {
  width: 50px;
  &.fill#red {
    color: red;
  }
  &.fill#blue {
    color: blue;
  }
}
```

Being used on markup like this (rendered with React):
```
<div class={`${styles.bucket} ${styles.fill}`} id="red">
    I should be red
</div>
<div class={`${styles.bucket} ${styles.fill}`} id="blue">
  I should be blue
</div>
```

The `bucket` and `fill` rules work, but the `red` and `blue` rules do not, because the id selector gets namespaced. This is a surprise to me, I did not expect css modules to namespace ids, nor does it seem right, at least not desirable in my case, but maybe I misunderstand. In my case changing the `id` is not right, so the workaround is to only style using class names and add an additional class to the markup:
```
  &.fill.red { }
```
```
  <div class={`${styles.bucket} ${styles.fill} ${styles.red}`} id="red">
```

**Comment by dvkndn** [comment]
Hi @aaronbeall , if you want to use id:

1. Namespaced class + Global id:
```css
.bucket:global(#red) {
  color: red;
}
```
```js
<div class={styles.bucket} id="red">
    I should be red
</div>
```

2. Namespaced class + Namespaced id:
```css
.bucket#red {
  color: red;
}
```
```js
<div class={styles.bucket} id={styles.red}>
    I should be red
</div>
```

**Comment by aaronbeall** [comment]
Thanks for the suggestions. I went with just adding class names (namespacing the #id would break other parts of the app).

So I take it namespacing the #id is an intentional feature of css modules? I was just surprised because I didn't see any mention or example of this in the readme, and it *seems* undesirable (since IDs are identifiers that have meaning well outside of styling, for example accessibility), FWIW.

Otherwise I'm loving css modules. :) Thanks!

**Comment by eduardoinnorway** [comment]
The first line of the css modules spec should be "Forget about #id, use .classes instead" :)

**Comment by lsdsjy** [comment]
For those who wants to avoid transform id selectors, you can manually modify the package `postcss-modules-local-by-default', find the line "case '#id':" and add `break;' after it, which seperates the processing of id selectors and class selectors.

**Comment by AsaAyers** [comment]
I ran into this problem when I was trying to use the ID and `for=` to assign grid areas. 

```
label[for='exampleId'] {
  grid-area: exampleLabel;
}
#exampleId {
  grid-area: example;
}
```

I think this seems like a pretty good strategy for assigning grid areas because I don't have to add any extra classes. I can just use the markup that I should use for accessibility anyway.
I was surprised to discover that the ID is transformed and the `for=...` that references the ID doesn't. Even if I do use `id={styles.exapleId}` in my code, that label's selector will never work. 

```
label[for='exampleId'] {
  grid-area: exampleLabel;
}
#_exampleId_dhveb_1 {
  grid-area: example;
}
```


I'm going to go ahead and just use `:global(#exampleId) { ... }` for my project. IDK if its possible, but if IDs are being transformed, it would be really nice to have the `[for=...]` transformed too. I don't know of any other selectors that always refer to an ID.
