### ISSUE TITLE
dynamic import() not loading CSS Modules

### ISSUE THREAD

**Issue by matheusml** [css-modules/css-modules#232]
I'm trying to add a dynamic import() to my React component, and their working fine. Except for one huge detail: only the JavaScript is being loaded but the CSS, provided by CSS Modules, aren't.

Here's the code:

```js
import React, { Component } from "react";
import { BrowserRouter as Router, Route } from "react-router-dom";

class Routes extends Component {
  constructor(props) {
    super(props);

    this.state = {
      home: null
    };
  }

  componentDidMount() {
    import("../home/Home").then(Home => this.setState({ home: Home.default }));
  }

  render() {
    return (
      <Router>
        <div>
          <Route exact path="/" component={this.state.home} />
        </div>
      </Router>
    );
  }
}
```

React: 15.5.4
Webpack: 2.5.1

**Comment by kafkahw** [comment]
I'm having the same issue. (Using react 15.5 and Webpack 2 too)
I think in the above example it's because we lazy load/import "Home" element, which makes extract-text-webpack-plugin not be able to extract css that is imported into "Home". If you take a closer look at your chunk files, I bet you'll find that the css styles are present in the chunk file for "Home". However, looks like those styles in chunk.js file can not be recognized by the browser. I feel we need another webpack plugin to extract those styles out of chunk.js and put them into a chunk.css file.

**Comment by matheusml** [comment]
@kafkahw you just have to put 'allChunks: true' in ExtractTextPlugin in Webpack

**Comment by kafkahw** [comment]
Thank you @matheusml ! Just saw yourself's answer to your same question at StackOverflow lol.
