### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by knownasilya** [css-modules/css-modules#3]
Is this possible with browserify? Would love an example if it is.

**Comment by sokra** [comment]
Currently not. Currently CSS Modules are only possible with webpack.

But @joshgillies want to write a browserify transform once we get the stuff ready: https://github.com/webpack/css-loader/issues/60#issuecomment-105509362

**Comment by shama** [comment]
@knownasilya There is https://github.com/shama/webpackify ;)

**Comment by knownasilya** [comment]
Sweet! I'll see how that works!

**Comment by geelen** [comment]
I'm currently writing the JSPM loader implementation, and Browserify shouldn't be too difficult for someone who understands the internals. Basically, all the syntax transformations are being done by the three PostCSS plugins: `postcss-modules-local-by-default, `postcss-modules-extract-imports` and `postcss-modules-scope`. But then the file contains `:import` and `:export` primitives, which aren't documented outside of https://github.com/webpack/css-loader/issues/60. *That's* what needs to be specialised between Webpack/JSPM/Browserify, and then the whole package needs to be bundled up into an easy-to-install project.

Btw, by dropping `postcss-modules-local-by-default` off the chain, you get opt-in CSS Modules behaviour, since the other two plugins look for `:local` directives before they do anything. But when both Webpack & JSPM have loaders, it'll be easier to follow.

**Comment by serapath** [comment]
I'm not sure if that solves the same problem, but are you aware of [atomify](http://github.com/atomify)?

You can create a project called `mybuttoncss` that contains just:
* index.css
* package.json

and publish it to `npm`. Then, in another project `buttontest` you do: `npm install mybuttoncss` and in that projects `buttontest/index.css` you write:
```css
@import 'mybuttoncss'
/* ... */
``` 

### Advanced
If you want to pass variables around, you can just define in `mybuttoncss` project:
```css
/*[mybuttoncss/index.css]*/
:root {
  --mybuttoncss1: #ff0000;
  --mybuttoncss2: 50px;
  /* .... */
}
body {
  background-color: var(--mybuttoncss1);
  font-size: var(--mybuttoncss2);
}
```

and then in `buttontest`
```css
/*[buttontestProject/index.css]*/
@import 'mybuttoncss'
root: {
  --mybuttoncss1: green;
  --mybuttoncss2: 15px;
  /* .... */
}
```

If you in general stick to BEM conventions in all your modules, it works quite fine and the project can in general be extended with a lot of `rework plugins` and in the the future `postcss` is planned. There is already support for `autoprefixer` :-)

**Comment by geelen** [comment]
There is now https://github.com/css-modules/css-modulesify and https://github.com/css-modules/browserify-demo, so I'm going to close this issue and discussion can continue on one of those projects.
