### ISSUE TITLE
Convert selector names to camel case

### ISSUE THREAD

**Issue by roman01la** [css-modules/css-modules#4]
Are there any reasons to not do this by default? This would fit existing CSS written with hyphens and underscores. Also in JavaScript dot notation feels better: `s['box-js_blue']` vs `s.boxJsBlue`.

**Comment by geelen** [comment]
I think any kind of rewriting/translation would be a bad idea here. If you write `.x`, you should get "x" in JS, for all values of x. If you want camel-cased vars in JS, write camel-cased class names in CSS.

Furthermore, the reason so many classnames have `-` and `_` as punctuation are because you're trying to make them not clash with others in a global namespace. CSS Modules explicitly target that problem. So you no longer need, `.Block_Element--modifier`, just use `.LocalName` and CSS Modules will make sure it doesn't clash.
