### ISSUE TITLE
import className from fileName

### ISSUE THREAD

**Issue by ChristopherBiscardi** [css-modules/css-modules#40]
Let's say I have a file in an npm module as such:

```css
/* Card.css in the npm module `cards`*/
.card {
  background: white;
}
```

In another project, I want to target `.card` from `cards`.

```css
/* Thing.css */
.row {
  /* some random grid stuff */
  .card from "cards" {
    grid-width: 1/3;
  }
}
```

I've seen `:import` from ICSS but have hanged my local setup (webpack, etc) trying to figure out how I can import an identifier from a different file.

Is this css-modules territory or should I look at other ways of importing the identifiers?

**Comment by NekR** [comment]
Seems like this one is dupe of #25

**Comment by ChristopherBiscardi** [comment]
@NekR I thought it might be, but #25 seems to be talking about importing variables such as colors. What I am trying to achieve seems more limited in scope since it is only for `.card` to be compiled to the same classname across two files.

**Comment by NekR** [comment]
@ChristopherBiscardi hmm.. I might be wrong, but card should be compiled with the same name anyway.

Okay, here when accesing ``.row`` from JS you will get class names of ``.row`` and ``.card`` in one string. If you will then create ``.row2`` and compose it with ``.card`` then ``.row2`` will use same class of ``.card`` as ``row`. Although I am not sure how this will work with external modules, but if you are using webpack and css-loader then I think everything should be fine.

```css
.row {
  composes: card from 'cards.css';
  /* some random grid stuff */
  grid-width: 1/3;
}
```

**Comment by cliffrowley** [comment]
This is rather good timing for me, I'm also having exactly this issue.  I'll post back with any success / failure.

**Comment by joshwnj** [comment]
If it's coming from an npm module `cards` should it be `composes: card from "cards/cards.css"` ?

**Comment by cliffrowley** [comment]
Ok, I've just tried using `composes` to solve this and I've stumbled on another issue before I can even test it.  I'm using sass (via sass-loader) and each of my component sass files imports a `utils.scss` a couple of directories down, which works fine without `composes`, but with it I am getting a file not found on the `utils.scss` from the file being imported for composition.

E.g. this is my directory structure:

```
src/
  components/
    Card.jsx
    Card.scss
    CardContainer.jsx
    CardContainer.scss
    ...
  sass/
    _utils.scss
    ...
```

My (simplified) `Card.scss` looks like this:

```
@import '../sass/utils';

.card {
  ...
}
```

My (again simplified) `CardContainer.scss` looks like this:

```
@import '../sass/utils';

.card {
    composes: card from './Card.scss';
}

.cardContainer {
  & > .card {
    ...
  }
}
```

The error I see is:

```
Module not found: Error: Cannot resolve 'file' or 'directory' ../sass/utils in <path to project>/src/components
```

I don't fully understand how this all fits together but It seems to me that this mechanism is trying to resolve a js/jsx file rather than going through the sass pipeline.  Does this make sense to you?  It's resolving `./Card.scss` just fine - it's the secondary import that doesn't seem to be working.

**Comment by ChristopherBiscardi** [comment]
@joshwnj Consider the second snippet in my original post as pseduocode. 

@NekR using composes as such:

```css
.row {
  composes: card from 'cards';
}
```

results in this JS object:

```javascript
{
 row: 'Thing__row___9NgKF Card__card___1RA4j'
}
```

which works perfectly, but is not what I'm trying to do.

----

What I am trying to do is render the following final css, where `Card__card___1RA4j` is an identifier defined in another file.

```css
.Thing__row___9NgKF {
  /* some grid stuff here */
}

.Thing__row___9NgKF .Card__card___1RA4j {
  grid-width: 1/3;
}
```

**Comment by joshwnj** [comment]
@ChristopherBiscardi i see, that makes sense thanks.

Would this give the result you're after?

```
.row { 
  /* grid stuff */
}

.card {
  composes: card from "cards";
}

.row .card {
  grid-width: 1/3;
}
```

**Comment by ChristopherBiscardi** [comment]
That produces:

```javascript
.Thing__row___9NgKF .Thing__card___1mL-s {
}
```

so it would work if I was using the `.card` from `Thing.css`, but what I want to do is target the `.card` from `cards`.

**Comment by joshwnj** [comment]
That's why I'm wondering, do you have a specific need to do that? In this case `.card` in `Thing.css` composes `.card` from `cards` so in your template when you do:

```
import styles from "./Thing.css"

`<div class="${styles.row}">
  <div class="${styles.card}" />
</div>`
```

it should give you the specificity of "a card inside a row" that you're after.  Or does that example not cover some of the functionality you're after?

**Comment by ChristopherBiscardi** [comment]
The specificity desired isn't "**a card**, inside a row" it's "**the card class from cards**, inside of a row".

To expand on this a bit, let's say I am rendering this `Card` React element, which comes from (for all intents and purposes) a third party node module named `cards`.

```javascript
// Card.jsx

import React, { Component, PropTypes } from 'react';
const { string } = PropTypes;
import styles from './Card.css';

export class Card extends Component {
  render() {
    return <div className={styles.card}>{this.props.children}</div>
  }
}
```

```css
/* Card.css */
.card {
  background: white;
}
```

The usage (in an app) would look something like this:

```javascript
import React, { Component } from 'react';
import Card from 'cards';
import styles from './App.css';

class App extends Component {
  render() {
    return (
      <div className={styles.row}>
        <Card><p>stuff here</p></Card>
        <Card><p>stuff here</p></Card>
        <Card><p>stuff here</p></Card>
        <Card><p>stuff here</p></Card>
      </div>
    )
  }
}
```

Which brings us to `App.css`.

```css
.row {
  lost-center: 968px;
  .card from "cards" {
    lost-column: 1/4;
  }
}
```

So specifically, I'd like to target the `card` class from `Card.css` inside `App.css`.

**Comment by joshwnj** [comment]
I see, thanks for clarifying. So in this case the `Card` component doesn't allow you to supply your own `className`.  If it did we could sidestep this issue altogether.

At the moment there's no support in css-modules for using `.card from "cards"` as a selector.  It's not out of the question, but I'm trying to think through the ramifications.  

To use this approach would involve a fair bit of knowledge about the internals of the 3rd-party module, correct? You'd need to assume that it was also using the same version of css-modules, otherwise the className `Thing.css` gets for `.card` won't be guaranteed to match the className that the `<Card>` component applies to its children.

I think this is where [ICSS](https://github.com/css-modules/icss) comes into play. If a 3rd-party module was distributed with styles and classNames in this common format there would be less assumptions involved. 

Is this the kind of thing you had in mind?

**Comment by ChristopherBiscardi** [comment]
> If it did we could sidestep this issue altogether.

Indeed. In this specific case I control all of the relevant code and could add the className support, but the intent is to distribute a set of abstractions as modules themselves. Part of this is exploring where the boundaries actually lie in terms of what has to be packaged with what (clearly that would mean shipping today would mean implementing className support, which I already have a working model of). Ideally I'd like to build upon this to create elements which can work as a group or individually without requiring passing new classes around. Which leads to:

> To use this approach would involve a fair bit of knowledge about the internals of the 3rd-party module, correct?

Yes, it would. Rather, it would except for the fact that the constellation of element packages will all be built on a common base; Which makes the base assumptions a known quantity shared across all elements. There are other significant facets, such as the style of grid system that lost grid is, etc. but all that is stuff I'm finalizing *after* I figure out the base issue of "Can elements integrate deeply with other elements based on pre-existing class names".

> You'd need to assume that it was also using the same version of css-modules

The elements are being distributed as raw code (ie: as pre babel and pre PostCSS compilation processes) rather than pre-compiled for various other reasons, such as enabling per-project configuration of constants such as "default grid width", "media query bases" and "default border radius". The intent being to enable deep theming, "element collections" (roughly analogous to a Bootstrap, Foundation, Semantic, etc), among other things. As a result, they will all be compiled at the same time, with the same version of css-modules. (pre-compilation for use as raw css is an interesting discussion topic I've explored briefly but is not currently the focus).

> I think this is where ICSS comes into play. If a 3rd-party module was distributed with styles and classNames in this common format there would be less assumptions involved.
> Is this the kind of thing you had in mind?

yes, pretty much, although I don't know if ICSS is the solution. How would one go about distributing as ICSS? I haven't come across any "Dump ICSS" debug options, icss-loader, etc.

**Comment by joshwnj** [comment]
> How would one go about distributing as ICSS?

I don't know of any examples of this, just thinking ahead of possible solutions :)

Thanks for sharing the context of the problem you're trying to solve, that makes more sense now.

**Comment by NekR** [comment]
hmm.. modifying classes from another modules seems like violation of module principles. While this all makes sense in _global_ CSS, it does not makes sense in CSS Modules since the idea is to eliminate such side effects. Image that you could modify a constructor of imported class and this will affect all other users of that class. Looks like a mot such a best practice, right? What is common in OOP is _inheritance_, and while it's called differently, _composition_ from the CSS Modules is almost the same. e.g. to be able to modify (override) ``Card`` class in your code, you need to _inherit_ from original ``Card`` and then use that subclass across your application. I believe same applies for ``.card`` and _composition_.

P.S. I understand that ``Card`` is React class and it provides already an interface to modifying/customizing it, but this is just an implementation detail of that class.

**Comment by ChristopherBiscardi** [comment]
@NekR 

>  modifying classes from another modules seems like violation of module principles.

I disagree. We can have clear `:export` and `:import` semantics through ICSS, which means that we can think about CSS as an API contract just like any other module's exports. Using the exported classes in a JavaScript file is no different from using the exported classes in a CSS file.

> and this will affect all other users of that class

The usage I'm proposing doesn't affect all of the instances of `.card`, just the ones I choose to affect (the ones inside of `Thing`'s `.row` in this example). Regardless, it's also possible to not modify `.card` in this interface, but use the imported `.card` as scoping for a different element I've created in another place:

```css
card from ~cards .myOtherThing {
  background: blue;
}
```

> e.g. to be able to modify (override) Card class in your code, you need to inherit from original Card and then use that subclass across your application.

It depends. The "class extends" syntax is relevant in one sense, but in the other we're just talking about passing in different props (a `className` or a `heading`, etc), which requires no inheritance. The sense that I'm talking about is positioning the card in a grid, which is not the responsibility of the `Card` imo but rather the container in which the `Card` is being rendered. Especially with the usage of lost grid, I'd like to express the constraint as "The `Card` inside of this row is 1 column of a 4 column grid", which is most easily expressed as

```css
.row {
  lost-flex-container: row;
  .card {
    lost-column: 1/4;
  }
}
```

Expressing the constraint in this way would require no additional "html" markup as such:

```html
<div className={styles.row}>
  <Card><p>stuff here</p></Card>
  <Card><p>stuff here</p></Card>
  <Card><p>stuff here</p></Card>
  <Card><p>stuff here</p></Card>
</div>
```

whereas the alternate solutions (`className` and containing divs) require additional markup.

```html
<div className={styles.row}>
  <Card className={styles.col}><p>stuff here</p></Card>
  <Card className={styles.col}><p>stuff here</p></Card>
  <Card className={styles.col}><p>stuff here</p></Card>
  <Card className={styles.col}><p>stuff here</p></Card>
</div>
```

```html
<div className={styles.row}>
  <div className={styles.col}>
    <Card><p>stuff here</p></Card>
  </div>
  <div className={styles.col}>
    <Card><p>stuff here</p></Card>
  </div>
  <div className={styles.col}>
    <Card><p>stuff here</p></Card>
  </div>
  <div className={styles.col}>
    <Card><p>stuff here</p></Card>
  </div>
</div>
```

The className version:

```html
<Card className={styles.col}><p>stuff here</p></Card>
```

is acceptable to me for now, but it's clear that the semantics of `className` should be "total override of any previous className" rather than "styles which are applied in addition to the default styles. This means that `Card` now requires an empty containing div inside of the element, so the last two examples (`className` and containing divs) are *the same example* with the only difference being where the "extra div" is placed. Since the div itself is demonstrably unnecessary, except for the fact that the consumer doesn't have access to target the compiled class name, I'd like to not have it there.

**Comment by sokra** [comment]
> > modifying classes from another modules seems like violation of module principles.

> I disagree. We can have clear :export and :import semantics through ICSS, which means that we can think about CSS as an API contract just like any other module's exports. Using the exported classes in a JavaScript file is no different from using the exported classes in a CSS file.

You should only access exports in a readonly matter from other modules.

`.card from "./cards" { /* styles */ }` is a write access (in sense of CSS).

> > and this will affect all other users of that class

> The usage I'm proposing doesn't affect all of the instances of .card, just the ones I choose to affect (the ones inside of Thing's .row in this example). Regardless, it's also possible to not modify .card in this interface, but use the imported .card as scoping for a different element I've created in another place:
> 
> card from ~cards .myOtherThing {
>   background: blue;
> }

This would be a readonly access so it's propably valid. But I still say "don't do that" because couples your component with the other component. It's better to decouple it and i. e. provide a `scope` property for the `MyOtherThing` component.

> /* Thing.css */
> .row {
>   /* some random grid stuff */
>   .card from "cards" {
>     grid-width: 1/3;
>   }
> }

For this example I can image two solutions that looks valid:

`.row { & > .item { ... } }` with `<Row>` wrapping its children into `<div className="item">` (recommended).

Or `.row { & > * { ... } }`.

Both prevent coupling to the `<Card>` component.

---

Just a side note, but don't do that.

It's (should be) acctually possible to express `.card from "./Card"` with the underlying ICSS syntax:

``` css 
:import("./Card") {
  imported-card: card;
}

.row {
  & > .imported-card {
    /* styles */
  }
}
```

**Comment by cliffrowley** [comment]
I have also gone the className route for now - though I'm not happy with it.

**Comment by NekR** [comment]
> It depends. The "class extends" syntax is relevant in one sense, but in the other we're just talking about passing in different props (a className or a heading, etc), which requires no inheritance

This is why Web Components are one a way to decide to use CSS Variables or Custom Pseudo Elements, or even an ``@extend`` syntax which probably will use like current CSS Modules ``composes``, not SASS's ``@extend`` (although I am not sure about last here). One big plus in Web Components is that it supports ``class`` (and other common attr) for custom elements by default. Probably good solution would be to have one  master class (or mixin) which will implement ``className`` pass-though and then extend/mix that class/mixin to your components.

Anyway, this all is the _cost_ of the encapsulation. Which is heavier, but absolutely better. Look at current CSS...

**Comment by ChristopherBiscardi** [comment]
Closing this, since it seems like forcing old CSS habits into new tech and there are a few acceptable solutions which do not require modification of imported styles.

**Comment by Huxpro** [comment]
@ChristopherBiscardi 

Actually I thought you are right. What you want is just overriding the `.card` class in `<Card />` from `<App />`

In OOP, a sub class can override members in super class:

```javascript
class Card{
    doSomeThing(){
        console.log("I am a Card")    
    }    
}

class DerivedCard extends Card{
    // override doSomeThing() in Card
    doSomeThing(){
        console.log("I am a derived Card")    
    }    
}
```

Even React can do so by composition.
(Considered React as pure function and what it provides is just returning markup)

```javascript
class Card{
    render(){
        return <div />
    }
}

class DerivedCard{
    render(){
        return <div><Card /></div>
    }
}
```

What's similar to CSS Modules is like that:

```
.DerivedCard {
    .Card from ''./Card.css" {
        /*do some override*/
    }
}
```

With `compose:` we can got a `.DerivedCard` also, but It's not easy to pass it into a encapsulate React Component like `<Card />`, which not provide a `className` props which would passed into suitable position of rendered markups by default. 

if we can get a `.DerivedCard .Card`, that would be a real OOP style overriding.

**Comment by ChristopherBiscardi** [comment]
@Huxpro That does work with React, but I have found *very* few reasons to use overriding (iirc, even React's Component doesn't require you to override functions). It also increases the amount of files/code/etc that you need to look at to understand a given segment; increases the liability when changing the base class, etc. Essentially, I wouldn't advocate this approach in general.

Thus, I wouldn't suggest that approach for CSS either.

----

The "Recommended" approach previously mentioned in this thread works quite well:

```javascript
class Row extends Component {
	render() {
		return (
			<div className={styles.row}>
			{
				this.props.children.map(child => {
					return <div className={styles.item}>{child}</div>
				})
			}
			</div>
			)
	}
}
```

where the `Row` classes are like:

```css
.row {
  lost-flex-container: row;
  & > .item {
  	lost-column: 1/3 3;
  }
}
```

----

At this point, I fully agree that breaking encapsulation is not worth it when we have acceptable alternative solutions.

> Anyway, this all is the cost of the encapsulation. Which is harder, but absolutely better.

**Comment by Huxpro** [comment]
@ChristopherBiscardi  I can see you.

But sometimes what we want to override can not be done with just adding a wrapper. We can only override styles including `height`, `width`, `color` etc. by targeting directly to the inner nodes.

What I do now for working around, overriding component inner style is to export a 'className' props to do that:

```
import style from './Button'

export default (props) => (
    <button className={`${style[props.mode]} ${props.className || ""}`}>
        {props.children}
    </button>
)
``` 

I do not sure if that is a good practice although it works well.

As you said, maybe using nested selector is "forcing old CSS habits into new tech", but somethings I found is really common that we need **override** a component styles for easily layout, theming or tweaking styles in building real world products.

**Comment by sergeylukin** [comment]
@ChristopherBiscardi @sokra and everyone, I think I have an alternative to solutions that were already discussed here. There is a chance it deserves your attention, so please check out this simplified demo: https://jsfiddle.net/n0cap6pz/1/
I added brief explanation there + I thought live demo would provide more insight rather than trying to explain my idea here. I hope I understood your discussion correctly and that my demo is relevant. Let me know if you have questions or counter ideas. I'd love to expand on this topic as I believe there is yet so much to learn about it.
Cheers

**Comment by nkbt** [comment]
@sergeylukin I am not quite sure what I was looking at. I mean, what was the point? If relying on context, then I would oppose it a lot.
Everything else seems like just an any other react app and I am missing the point.

PS: my point is still the same, no nesting, no overriding, only flat simple css files for each component independently.

**Comment by sergeylukin** [comment]
@nkbt Sure, I'll try to explain. There are usecases where a component should look different if used inside another component / inside a specific visual state of another component. A port of Foundation Grid is a good example in my opinion (ported & slightly adjusted from http://foundation.zurb.com/sites/docs/grid.html#collapse-uncollapse-rows):

```
<Row mediumCollapse largeUncollapse>
  <Column small={6}>
    Removes gutter at medium media query and returns gutter at large media query
  </Column>
  <Column small={6}>
    Removes gutter at medium media query and returns gutter at large media query
  </Column>
</Row>
```

Note that besides `<Row>` changing it's styles depending on flags used (`mediumCollapse` and `largeUncollapse` in this case), `<Column>` children should also change their styles accordingly.
So the simplified fiddle I posted above is all about approaching such usecases. Hopefully that makes sense.

Keen to know how you'd approach this.

**Comment by nkbt** [comment]
@sergeylukin the approach we are using: if components look differently - those are different components.
If `Row` is different - we create different `Row` component.

```js
import {Row, Column} from 'my-awesome-grid';

// ...

<Row>
  <Column>
    Boring cell
  </Column>
</Row>
```

And in the other place

```js
import {Row, Column} from 'my-awesome-collapsible-grid';

// ...

<Row>
  <Column>
    WOW, SUCH COLLAPSIBLE
  </Column>
</Row>
```

**Comment by nkbt** [comment]
In general, the principle is simple: `LESS configuration - MORE composition`

**Comment by joshwnj** [comment]
> if components look differently - those are different components

I like this approach too! 

If you let child-elements alter themselves based on the context they are in, it's much harder to know what all of the possible permutations could be.

There's a tradeoff. Doing it as @nkbt suggests may mean you have to create more component variations yourself, but in return it means you are dealing with a fixed number of possible outcomes rather than a potentially infinite number.  Creating these component variations is also something that can easily be programmed away.

**Comment by nkbt** [comment]
Thanks, @joshwnj 

Illustration to what I am talking about:

![20160407-105449](https://cloud.githubusercontent.com/assets/175264/14337217/2f640a6a-fcaf-11e5-9fe2-f3c3ec5be708.png)

**Comment by sergeylukin** [comment]
@nkbt @joshwnj thank you for your feedback and suggestions. I think I'd have to create much more components than I have now if was using such composition technique, which drives me away from it a bit. However, I guess I have yet to reveal the difference between 2 approaches discussed above on a bigger scale. I will play more with components composition as @nkbt suggested to better understand the pros and cons in different use cases.

**Comment by nkbt** [comment]
@sergeylukin 👌 Feel free to ping me in reactiflux (nkbt) or gitter.im/nkbt if you need

**Comment by MarkMurphy** [comment]
@ChristopherBiscardi 
> but it's clear that the semantics of className should be "total override of any previous className" rather than "styles which are applied in addition to the default styles.

That's how I feel about it but I guess that too is just an implementation detail. For example, you could implement a property in your component that tells it how to handle any className it receives as property. ie. to append or overwrite (where the default might be to append)

**Comment by geelen** [comment]
I just re-read the entirety of this thread on a flight — it's a fantastic discussion. Thanks to @ChristopherBiscardi for kicking it off and everyone for putting forward really good points.

I've been thinking about this a lot recently and gearing up to give a talk about theming in CSS Modules at CSSConf Budapest in 2 weeks (omg!). So I'm going to put together some thoughts that follow on from this thread and a few others and invite you all for feedback. At this point I think CSS Modules _does_ need to be extended in some way, but I'm still balancing the alternatives before I make a proposal.

**Comment by liady** [comment]
@geelen You can also take a look in thread #139  (2 suggestions for overriding children styles API).
Good luck in the conference!

**Comment by jquense** [comment]
I'd like to voice my desire to be able to extend imported classes via descedent selectors. I see that there are alternatives but there all seem really fragile, verbose, or incapable of scaling beyond a few variants.

imo it should be easy enough to do:

```
.toolbar > .btn-defined-elsewhere {
  margin-left 10px
}
```

Without having to create an entire new variant of Button specifically for use inside a toolbar. We'd end up with like 40 different button components which seems less than ideal, and sort of silly. I think its should be fair to consider extension via selectors a completely reasonable approach here. thanks for all the hard work folks!

**Comment by liady** [comment]
The reference can even be in the selector level:

```scss
/* MyList.scss */
.listItem :external(button from './MyButton.scss') {
  font-size: 17px;
}
/* this will generate ".listItem_[hash] .button_[hash] {}" rule */
```
And that way even the child element can have a specific rule for when it is inside a container:
```scss
/* MyButton.scss */
:external(listItem from './List.scss') .button {
  font-size: 17px;
}
/* this will generate ".listItem_[hash] .button_[hash] {}" rule */
```

**Comment by nkbt** [comment]
I feel like if the site needs 40 different buttons, then something should
probably be addressed in the design part of it.

But of course the abstraction we use is closer to petehunt/jsxstyles
conceptually (and uses css-modules as implementation detail) and might not
be perfect for everyone.

**Comment by jquense** [comment]
> I feel like if the site needs 40 different buttons, then something should
probably be addressed in the design part of it.

Well that's sort of my point :P, the excess variants are result of the composition model, not the need for many buttons. We have maybe 3 different buttons but in the context of a non-trivial application, the composition style suggests that I need to have a new button variant for each possible use with another type of component, (PageButton, NavbarButton, ToolbarButton, ListItemButton, DropdownButton, etc.) In order to apply context specific styling such as the margin example above.

**Comment by geelen** [comment]
@jquense I'll be addressing that in my (upcoming, now thousands of words long) post. Sorry it's taken a while to prepare!

As a sneak preview, I'm suggesting you could use this:

```css
.toolbar > * {
  margin-left: 10px;
}
```

Maybe `> *` isn't the best for that component, so you could try one of these as well:

```css
.toolbar > button { margin-left: 10px; }
.toolbar > :nth-child(2) { margin-left: 10px; }
.toolbar > * + * { margin-left: 10px; }
```

This way you don't have to create multiple Button components, but nor do you couple your `.toolbar` to the components it contains. It just sets the margin for its children, it doesn't care what children you give it.

That make sense?

**Comment by jquense** [comment]
it makes sense, but it feels like a step backwards. Using tag or universal selectors seems like the opposite of the spirit of the css modules.

It accomplishes what I want but offers less semantic clarity than a descendant selector against a class, while also being really brittle. 

Since the selector approach essentially does the same thing as the proposal here, why not codify it and adopt the suggested import semantic? Being able to import another class makes the whole thing explicit and the dependency clear as opposed to implicit with the tag selector

**Comment by elado** [comment]
@geelen 

`> button` isn't bulletproof because tags can change (e.g. `div` to `span`, `button` to `a` etc). Why does the wrapping component need to be aware of internal implementation of the inner component? (other than its classname)
`> nth-child(2)` or `> * + *` will fail if things are dynamic (e.g. a `<Header>` with signed in/signed out/has notifications states)
`> *` is too generic and may fail if other components are being added

**Comment by Zequez** [comment]
Is there still no way to accomplish this? Seems very counter-productive the need to create themable components and having to add an extra composition layer just to change a nested component visual style. I don't think we should have to worry about minor style changes in the logic layer of the application, we should only need to use JS to change the behavior not the looks.

Even quite big and popular projects like [react-toolbox](https://github.com/react-toolbox/react-toolbox) that use modular CSS and themable components need to [constantly break the rule by having to match [data-react-toolbox] in the CSS](https://github.com/react-toolbox/react-toolbox/search?utf8=%E2%9C%93&q=data-react-toolbox).

Honestly, by not being able to do this, we're just overcomplicating things.

**Comment by Tomdye** [comment]
I am currently having the same issue when assessing our use of `css-modules` within the dojo 2 toolkit. We are considering using css modules to ship structural styles along with our widgets and themes in a separate repo. In order to use the generated class names at build time we would need to be able to load class names from the structural files into the theming files. Otherwise we'd have to fall back to custom tag names, or adding separate class names specifically for theming which will break the encapsulation that css modules provides.

**Comment by Billy-** [comment]
Hi all, have just come across this issue. Has there been any updates on this?

Kind regards,

**Comment by vinpac** [comment]
Any update?

**Comment by tivac** [comment]
`:external(...)` has been working well for us the few times we've needed this capability when using `modular-css`.

**Comment by arahansen** [comment]
@tivac could you provide an example of how this works? That syntax doesn't seem to do the trick for me. Is there an additional loader I need in place?

**Comment by tivac** [comment]
@arahansen I don't think CSS Modules ever added support for `:external`, I built my own thing for a variety of reasons and implemented it there.

https://github.com/tivac/modular-css/blob/master/docs/features.md#overriding-styles

**Comment by Reverbe** [comment]
any update?

**Comment by lawrencebla** [comment]
any update?

**Comment by tomdye** [comment]
@nkbt that's essentially what we have adopted for Dojo

**Comment by jquense** [comment]
@nkbt thats the same thing as `composes:`? The discussion here is the need for an API that allows selecting for a class e.g. `.toolbar > .button {}` vs `.toolbar > .form-control {}` which is not possible by either existing means but generally required (albeit infrequently)

**Comment by nkbt** [comment]
@hrasoa if you want composition of component styles, you need to act like you do with components, to step above and compose them. So it would be something like

App.js
```jsx
import css from 'App.css';
export default () => (
  <div>
    <Cover className={css.cover} />
    <Content className={css.component} />
  </div>
);
```
With support of `className` in each component respectively.

I do believe that idea of doing `.cover + .content` *inside* either of those components is straight up incorrect, since components should be able to work in isolation and not know anything about any adjacent components. Only parent should be able to compose components *and* their styles if styles depend on composition.

**Comment by nkbt** [comment]
@jquense we do not use `composes:`, it's pretty much unofficially banned from being used entirely. Each css is self contained and never aware of any other things on a page except its own component. For theming we use `var()` which works perfectly fine in all modern browsers we support. For any styles that depend on multiple component - we step above and style element that composes those components instead (see my previous comment for example of that)

In this way we are as close to StyledComponents as it is technically possible. Like full on "css-in-js" but with nice and familiar CSS syntax with all its advantages and no drawbacks.

**Comment by hrasoa** [comment]
@nkbt the issue is that ```.cover + .content``` now got duplicated on both Cover and Content compiled styles. Sorry if I don't seem to understand how to think css-modules way as I'm really new on this.

**Comment by jquense** [comment]
Ya'll if anyone wants to see this happen, I think it think it should. Having used css-modules exclusively for the last few years on large and small projects there are definitely valid use cases for it. 

The issue here is there isn't anyone to work on this, so if someone wants to see it happen, the best way forward would be to show up with a PR. no one is really working on css-modules anymore, i think it just takes someone who wants to do the work, see: https://github.com/css-modules/css-modules/issues/187 and https://github.com/css-modules/css-modules/issues/187

**Comment by anagamidev** [comment]
SomeComponent.module.scss
```scss
.header {
  color: #000000;
}
```
SomeOtherComponent.module.scss

```scss
@value header from  './SomeComponent.module.scss';
$imported-header: header;

.someOtherComponent .#{$imported-header} {
  color: #0000ff;
}
```
