### ISSUE TITLE
css className conflict

### ISSUE THREAD

**Issue by chenxsan** [css-modules/css-modules#48]
Just set up a repo https://github.com/chenxsan/css-module-class-conflict to demo this problem, I had these css codes

```
.title {
  composes: small from './border.css';
  composes: small from './borderRadius.css';
}
```
in [app.css](https://github.com/chenxsan/css-module-class-conflict/blob/master/styles/app.css), expected the exported class name to be `border__small__xxxxx borderRadius__small__xxxxx`, but i got this:

<img width="872" alt="screen shot 2015-09-08 at 16 19 59" src="https://cloud.githubusercontent.com/assets/1091472/9729963/e4726a02-5645-11e5-88a1-5438c2b610f8.png">

I got two `borderRadius__small__xxxxx`, the first `small` was overwritten by the second `small`.

Is this an expected behavior?

**Comment by saintwinkle** [comment]
Because you have assigned variable 'small' twice.
Try to use 'smallA' and 'smallB', or something else to make a distinction.

**Comment by NekR** [comment]
@saintwinkle What? This breaks all the concepts of the encapsulation/modules. ``small`` is not variable, but _key_ (read css class) in both ``border.css`` and ``borderRadius.css``. Having ``smallBorder`` and ``smallRadius`` in css files mean that then there is not sense to CSS Modules at all (since class names are not unique).

If this really happens, then it's just a bug. Bad bug, but still simply a bug (and not conceptual _feature_).

**Comment by sokra** [comment]
That's my fault. Try to delete this lines: https://github.com/webpack/css-loader/blob/master/lib/processCss.js#L146-L148
