### ISSUE TITLE
How to pass variable to common CSS classes

### ISSUE THREAD

**Issue by nsisodiya** [css-modules/css-modules#50]
I recently adopted css-modules

``` css
.boxShadow {
    -moz-box-shadow: inset 0 -2px 0 rgba(0, 0, 0, .05);
    -webkit-box-shadow: inset 0 -2px 0 rgba(0, 0, 0, .05);
    -webkit-tap-highlight-color: rgba(169, 3, 41, .5);
}
```

this boxShadow class I have defined in common style.css. I am reusing `composes` at several places.
at some places, I want to use -3px instead of -2px. and Instead of rgba(0, 0, 0, .05) I want to use a separate color. 
Currently I am creating multiple version of .boxShodow like .boxShadowBlueStyle, .boxShadowRedStyle.

**Comment by serapath** [comment]
There was an `issue` earlier, see [#18](https://github.com/css-modules/css-modules/issues/18)

It's kind of related and I still don't know the answer to the problem.
I switched to a module called [`jss`](https://github.com/jsstyles/jss), because it gives me all the flexibility i need.

It allows:
* defining component based stylesheets (parameterized, because its javascript)
* updating a components stylesheet at runtime (even individual properties)
* author your styling in `css` or in `css es6 template strings` and use [jss-cli](https://github.com/jsstyles/jss-cli) to convert it to `jss` on the fly

**Comment by rpominov** [comment]
You can use any css preprocessor before applying css-modules, like sass, less, or stylus. And use variables system from that preprocessor.

We do `stylus -> autoprefixer -> css-modules` and it works pretty nice for us.

**Comment by serapath** [comment]
How do you update those variables at runtime?

**Comment by rpominov** [comment]
Maybe I didn't understand original question right, but I think @nsisodiya didn't want to update them at runtime.

**Comment by serapath** [comment]
I'd like to do that and afaik an es6 import or commonJS require call can get me the generated class names to add them, for example, to my "jsx markup".
It might be awesome to pass in or update "style variables" at runtime.

**Comment by nsisodiya** [comment]
I can use `compass` -> `css files` -> `css-module`.
only problem I am having, I do not want to keep generated css files in this flow.
currently I am having .css files in code repo. If I move to scss then I will keep only scss files and generated css files will go in /temp folder, in this case, referencing will be bit difficult. 
currently I have having one js file and one css file per component folder.

**Comment by NekR** [comment]
With webpack you do not need all those tricks. Just use pipe of loaders.

**Comment by rpominov** [comment]
Yeah, webpack makes it easy to use transformation pipeline as long as you want. You just specify in config that you want `stylus -> autoprefixer -> css-modules` for `*.styl` files, for example, and then simply do:

```js
css = require('file.styl')
css.myClass // contains name of class `.myClass` from `file.styl`
```

Probably similar can be done with browserify.

**Comment by jeron-diovis** [comment]
@rpominov Do you use `composes` statement from css-modules in your stylus code, or you decided to don't use ever?
I tried similar pipeline with Sass. Have following files:
```sass
// mixins.scss
@mixin myMixin {
  ...
}

// style1.scss
@import "mixins.scss";

@include myMixin;

.someClass { ... }

// style2.scss
.anotherClass {
   composes: someClass from "style1.scss"
}
```
This simple code fails with 
```
Module not found: Error: Cannot resolve module 'mixins.scss' in /path/to/style1.scss
```
After removing `composes` from `style2.scss` everything just works. 

So, do you use css-modules **only** for providing unique classnames, without any additional features, and prepocessor for everything else?

**Comment by rpominov** [comment]
> So, do you use css-modules only for providing unique classnames, without any additional features, and prepocessor for everything else?

Yeah, basically this. I haven't used it very long yet, but so far I needed only unique classnames.

**Comment by roylee0704** [comment]
I think the following README from `react-css-modules` might show-case how css preprocessors and css work together in webpack.

 https://github.com/gajus/react-css-modules#sass-scss-less-and-other-css-preprocessors

**Comment by roylee0704** [comment]
or it can actually be achieved without using any css-processors. Check this out: https://github.com/MadLittleMods/postcss-css-variables

**Comment by StevenIseki** [comment]
The best approach I have found so far is to export your variables as `@value`'s 

**colors.css**

```css
@value blue: #0c77f8;
@value red: #ff0000;
@value white: #fff;
```

**header.css**

```css
@value colors: "./colors.css";
@value blue, white, red from colors;

.header {
  color: blue;
  background-color: red;
}
```

Using [postcss-modules-values](https://github.com/css-modules/postcss-modules-values) plugin

**Comment by serapath** [comment]
If you compare it with javascript it basically means that instead of `requireing` or `importing` X, thus re-using X and "customize" it to your needs (=calling a function with arguments)....

While you **write** X (e.g. define a function in javascript), you already `import` or `require` all the arguments you might need...

While writing `header.css`, how can i possibly know all the scenarios in which i want to use it?
Maybe I could look about everything that is imported by the modules I will use and just overwrite `color.css` in my new project - but does that work if you have nested dependencies?

For me, when writing re-usable components, the approach css-modules take doesnt work for me and variables or the lack of passing in arguments when importing a css file is only one reason. Another one is dynamically adapting styling based on user interaction, so i switched to `jss` for now.
There it's easy to use variables, so I can write something like:
```js
module.exports = function header (params) {
  return `
    .header {
      color: ${params.blue};
      background-color: ${params.red};
    }
  `
}
```
Then when re-using my component somehwere else :-)
```js
var colors = { blue: '#0c77f8', red: '#ff0000', white: '#fff' }
var header = require('./header')(colors)
// use css2jss and jss to attach header css template string to DOM
// write rest of custom module that uses the "header module"
// ... 
```

**Comment by aft-luke** [comment]
I use `stylus -> postcss-modules` to get the superior syntax and power magic powers that stylus offers. One important issue to note, though, is how much extra fluff this generates. Anything that uses stylus's `@import/@require` automatically receives *all* the styles that are imported, as well as *all* the styles that are `composed` recursively, in both directions. This generates enormous "modules" for each component, particularly if a `comopse` references a `@require` or vice-versa: https://github.com/css-modules/css-modules/issues/145 .

**Comment by kevinSuttle** [comment]
Here's something I ran into, using `composes` and `@value` from various files. 

```css
/* Themes/Kratos/Fonts.css */

.lightFontStack {
  font-family: "Helvetica Neue Light", HelveticaNeue-Light, "Helvetica Neue", Helvetica,
  -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans",  sans-serif;
  font-weight: 200;
}
```

```css
/* Themes/Kratos/index.css */
@value colors: "./Colors.css";
@value fonts: "./Fonts.css";
```

```css
/* Inputs.css */
@value Kratos: "./Themes/Kratos/index.css";

.inputField {
  composes: lightFontStack from Kratos.fonts; /* NOPE */
```

```js
CssSyntaxError: postcss-modules-scope: /css-loader!/[...]/Inputs/Input.css:8:3: referenced class name "lightFontStack" in composes not found
```
