### ISSUE TITLE
Why no selectors?

### ISSUE THREAD

**Issue by tslocke** [css-modules/css-modules#63]
In the [Welcome to the Future](https://github.com/gajus/react-css-modules) article, we're advised that "In CSS Modules each class should have all the styles needed for that variant". i.e.:

    .common { ... }
    .normal { composes: common; ... }
    .disabled { composes: common; ... }
    .error { composes: common; ... }
    
That's all nice and clean. However, what if I have multiple independent states that can be combined. E.g. I have an component that can be "active" and/or "selected":

    .common { ... }
    .normal { composes: common; ... }
    .selected { composes: common; ... }
    .active { composes: common; ... }
    .selected_active { composes: selected active; ... }
    
If there are three or more such things, it's going to get pretty ugly.

CSS selectors are a very powerful way to capture situations like this (and a thousand others) in a very elegant and concise way. If the editor is both selected and active, just put both the classes on there. i.e. use it the way it was designed to be used.

We've all been burnt at some point by selector bugs, and many have decided that complex selectors are just not worth it. Personally this always struck me as a great shame. I want that expressivity! 

The fact that we're finally talking about local vs. global CSS is like someone at last found the light switch. CSS selectors were never the problem. The problem was having everything global.

With local CSS, I should be able to just look at one small file of CSS at a time, and satisfy myself that there are no selector bugs. I no longer have to worry about the way these rules interact with every other damn rule in the entire codebase. That should mean that I am free to use all the nice features of CSS selectors, and still be able to sleep at night.

So... I guess I'm missing something? Why is it that we still need restricting rules like "each class should have all the styles needed for that variant"?

**Comment by NekR** [comment]
> CSS selectors are a very powerful way to capture situations like this (and a thousand others) in a very elegant and concise way. If the editor is both selected and active, just put both the classes on there. i.e. use it the way it was designed to be used.

Hmm.. just do it.

> Why is it that we still need restricting rules like "each class should have all the styles needed for that variant"?

I believe it's just up to you. If you feel that it's right in your situation, why not do it?

**Comment by tablatom** [comment]
True, I can just do it, and in fact, for now, I am doing just that.

So the reason for asking is that I want to learn. I figure there is some careful thought behind that advice which I'd like to understand.

**Comment by geelen** [comment]
Hey @tablatom you've hit the nail on the head already.

> We've all been burnt at some point by selector bugs, and many have decided that complex selectors are just not worth it.

One of the reasons for writing complex selectors, I feel, is that naming things was *hard* and therefore descendant & tag selectors get used because they're easy. And that leads to coupling between styling and DOM structure, as well as leakage of styles outside the element. So by saying "everything must be a single class" we're trying to steer people away from that case.

Of course, that gives us the problem of wanting to apply two local classes to an element. My inclination is that the one-class-only rule (using `composes` to bring styles from other places) is usually good enough for most cases, certainly if you're considering "variations" of a component (like the button example you quoted). But state classes are a little more complex, since they can combine in the way you described.

On the other hand, the whole point of CSS Modules is to let you keep using all the CSS selectors you and your team already understand. For instance, something like `:hover` is dead-simple in CSS and irritatingly complex in JS. So we're deliberately keeping that power around for situations that CSS Modules doesn't have a "better" way to do stuff. But then, so much of CSS is predicated around the selectors being global so it becomes confusing! :confused: 

You might be able to use attribute selectors here to separate *variants* of a component from *states* of a component?

```css
.base {}

/* Variants */
.normal { composes: base; /* ...  */ }
.alternate { composes: base; /* ... */ }

/* States */
.normal[data-state~="active"] { /* ... */ }
.normal[data-state~="selected"] { /* ... */ }

.alternate[data-state~="active"] { /* ... */ }
.alternate[data-state~="selected"] { /* ... */ }
```

You do lose the ability to use `composes` in those state selectors, though (composition only works in single class selectors), so maybe it is better to just have a bunch of top-level classes and then add multiple to the element in JS, like what https://github.com/gajus/react-css-modules does.

Anyway, this is a good question, so thanks for contributing to the discussion :+1:

**Comment by tslocke** [comment]
My takeaway from this is I'm going ahead and using multiple state classes.

The two problems you mentioned were coupling between styling and DOM structure, and leakage of styles outside the element. Local class names should solve the latter. As for decoupling css from structure, that's a goal I've always been a bit dubious about. Fine if you're doing simple typographic styles for document-ish content, but for UI components it's rarely possible to make changes to the markup and have the styling just work as is. I think there's limited payoff in striving for CSS decoupled from structure.
