### ISSUE TITLE
How to do a composes on :hover?

### ISSUE THREAD

**Issue by iDams** [css-modules/css-modules#80]
Hi guys,

I am struggling to understand how `composes` works.
I have a default color that I use everywhere in my application and I would like to use it on a `:hover` of an element. So I tried something like this but it doesn't work:

`.white-round-btn:hover {
  composes: yellow-bg from "css/colors.css";
}
`
I have the following error:

`Error: composes is only allowed when selector is single :local class name not in ":local(.white-round-btn):hover"`

I think it is explained here in the documentation but I don't understand well
>There can be multiple composes rules, but composes rules must be before other rules. Extending works only for local-scoped selectors and only if the selector is a single class name.

I understand this is not the right way to do it but how can I handle a hover with my default color?
Thanks!

**Comment by wyze** [comment]
Curious about this as well. This is ultimately why I switched away from css-modules. Once `composes` works with psuedo selectors, I can see myself switching back.

**Comment by themitchy** [comment]
+1

That's a huge limitation - unless theres some clever pattern not in the docs.

**Comment by geelen** [comment]
Sorry folks, `composes` simply _can't_ work from within a pseudo selector. Here's a long discussion on the topic: https://github.com/css-modules/css-modules/issues/33

The TL;DR is that the "CSS Modules Way" is to compose something that _has_ a pseudo selector attached.

```css
.red {
  color: red;
}
.blue-on-hover:hover {
  color: blue;
}

.foo {
  composes: red blue-on-hover;
}
```

The reason is that `composes` exports additional classes and that can't be dynamic in any way. We need to extract the salient information from #33 and make a documentation page about it. That issue is https://github.com/css-modules/css-modules/issues/41

For an alternative approach, you can look at https://github.com/css-modules/css-modules/issues/68. The new `@value` syntax can help. That's still lacking documentation but it is out there, read https://github.com/css-modules/postcss-modules-values for more info.

Going to close this as a matter of tidying up but feel free to reply if you have further questions. Sorry for the confusion around `composes`, it trips everyone up!

**Comment by themitchy** [comment]
Thanks @geelen! Values looks like it could help alot.  I'm thinking I need a `colors.css` with values and maybe a `transitions.css`...

No need to apologize, the patterns are starting to gel and you guys are doing great work!

**Comment by geelen** [comment]
Yeah it's all starting to solidify in my head but the information is scattered all over this issue tracker (and there's plenty of issues that never got a proper response) so needs a bit of consolidation. A work in progress!

**Comment by iDams** [comment]
Thanks @geelen.
postcss-modules-values is definitely a great solution
