### ISSUE TITLE
Question: Do we even need pre-css when css-modules is here?

### ISSUE THREAD

**Issue by roylee0704** [css-modules/css-modules#89]
Do we even need other pre-css like `sass`, or `less` when `css-modules` is here? I understand that if you are coming from an existing project, and that project been using other pre-css from the past, then its inevitable. 

But what if I'm starting a new project with `css-modules`, do I still need `sass`/ `less`? If answer is yes, what benefits does it bring to the table?

**Comment by joshwnj** [comment]
I'm sure there will be times when you want something like sass or less, as they might be just the perfect thing to solve your particular problem.

However in a lot of cases they may not be needed with css modules. We're currently at the tail-end of a very large react application and made a decision to start with css modules and only incorporate sass if needed. As it turned out we haven't yet felt it necessary. We did add [a css variables plugin](https://github.com/MadLittleMods/postcss-css-variables) to our postcss chain, but that's only because https://github.com/css-modules/postcss-modules-values wasn't available at the time :)

**Comment by StevenIseki** [comment]
@joshwnj How do you use the css variables plugin with css modules. I am trying to do the same thing, as I only want to reuse the variables feature from sass.

**colors.css**

```css
$orange:   #ff6600;
$blue:   #056ef0;
```

In my button.css file, how do I use composition so I can reuse the color variables in colors.css?

**button.css**

```css
.button {
    composes: * from '../styles/colors.css';
    background-color: $orange;
}
```

**Comment by StevenIseki** [comment]
actually @joshwnj I think I have found the answer, to export the variables as `@value`'s

I mentioned the approach over [here](https://github.com/css-modules/css-modules/issues/92#issuecomment-160496831). 

Thanks

**Comment by joshwnj** [comment]
Ah, beat me to it :) Glad you found the answer

**Comment by roylee0704** [comment]
Cool guys, recently I stumbled upon this. 


What about importing the entire `framework.css` into your `.css`?

In SCSS(sass), I can :

`scss
import '~framework.css'
```

**Comment by pveyes** [comment]
@roylee0704 I usually import the "global" css in the Page (js file), because I think that where it should be. 
```js
import './global.css';
import Style from './local.css';
```

You really don't want to import any css into another css file unless it's a variable declaration, that's how css module supposed to be, grouping your stylesheet into module

**Comment by harishv6665** [comment]
@pveyes 
I dont want to append the hash code for certain css files and make it global using css modules. I am using postcss and cssnext upon it. Could you help me in this?
